databases:
  - name: stellaxdb
    plan: free
    databaseName: stellax
    user: stellaxuser

services:
  - type: web
    plan: free
    name: stellax-web
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd stellaxBaseProject && python -m gunicorn stellaxBaseProject.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stellaxdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4