databases:
  - name: stellaxBaseProjectdb
    plan: free
    databaseName: stellaxBaseProject
    user: stellaxBaseProject

services:
  - type: web
    plan: free
    name: stellaxBaseProject
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn stellaxBaseProject.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stellaxBaseProjectdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4