# Generated by Django 5.2.1 on 2025-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
    ]
