# Generated by Django 5.2.1 on 2025-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="icon_hover_color",
            field=models.CharField(default="#1779db", max_length=20),
        ),
    ]
